name: Java Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Adjust the Java version as needed

    - name: Build with Maven
      run: mvn -B clean package  # You can customize this command as needed

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: target/*.jar
